pex_binary(
    name="test_client_gstreamer",
    entry_point="test_client_gstreamer.py",
)

pex_binary(
    name="test_client_gstreamer_no_middleware",
    entry_point="test_client_gstreamer_no_middleware.py",
)

pex_binary(
    name="test_client_http",
    entry_point="test_client_http.py",
)
