python_sources()

pex_binary(
    name="client_gstreamer",
    entry_point="client_gstreamer.py",
)

pex_binary(
    name="client_gstreamer_no_middleware",
    entry_point="client_gstreamer_no_middleware.py",
)

pex_binary(
    name="client_http",
    entry_point="client_http.py",
)
